[project]
name = "coderagents"
version = "0.1.0"
description = "coderagents using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.203.0,<1.0.0"
]

[project.scripts]
coderagents = "coderagents.main:run"
run_crew = "coderagents.main:run"
train = "coderagents.main:train"
replay = "coderagents.main:replay"
test = "coderagents.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
